name: build

on: [push, pull_request]

jobs:
  build_ios:
    name: Build iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run llvm/clang-format@shell
        run: |
          brew install clang-format
      - run: clang-format -style=file -i alipay_kit_ios/ios/Classes/*.h alipay_kit_ios/ios/Classes/*.m --dry-run
      - run: flutter --version
      - name: check alipay_kit_android
        run: |
          cd alipay_kit_android
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check alipay_kit_ios
        run: |
          cd alipay_kit_ios
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check alipay_kit
        run: |
          cd alipay_kit
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib example/lib
      - name: build example
        run: |
          cd alipay_kit/example
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter analyze lib
          flutter build ios --no-codesign

  build_android:
    name: Build Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: check alipay_kit_android
        run: |
          cd alipay_kit_android
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check alipay_kit_ios
        run: |
          cd alipay_kit_ios
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check alipay_kit
        run: |
          cd alipay_kit
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
#          flutter pub publish --dry-run
          flutter analyze lib example/lib
      - name: build example
        run: |
          cd alipay_kit/example
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter analyze lib
          flutter build apk --debug
